package com.runwaysdk.jstest.business.ontology;

@com.runwaysdk.business.ClassSignature(hash = 829224903)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Sequential.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class SequentialQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 829224903;

  protected SequentialQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.jstest.business.ontology.SequentialDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.jstest.business.ontology.SequentialDTO>)super.getResultSet();
}
}
