package com.runwaysdk.jstest.business.ontology;

@com.runwaysdk.business.ClassSignature(hash = 1417244200)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AlphabetAttributeRoot.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class AlphabetAttributeRootQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 1417244200;

  protected AlphabetAttributeRootQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.jstest.business.ontology.AlphabetAttributeRootDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.jstest.business.ontology.AlphabetAttributeRootDTO>)super.getResultSet();
}
}
