package com.runwaysdk.business;

@com.runwaysdk.business.ClassSignature(hash = -1944827653)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to Business.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class BusinessSystemBase extends com.runwaysdk.business.ElementSystem
{
  public final static String CLASS = "com.runwaysdk.business.Business";
  private static final long serialVersionUID = -1944827653;
  
  public BusinessSystemBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.system.metadata.MetadataRelationship addParentMetadata(com.runwaysdk.system.metadata.Metadata metadata)
  {
    return (com.runwaysdk.system.metadata.MetadataRelationship) addParent(metadata, com.runwaysdk.system.metadata.MetadataRelationship.CLASS);
  }
  
  public void removeParentMetadata(com.runwaysdk.system.metadata.Metadata metadata)
  {
    removeAllParents(metadata, com.runwaysdk.system.metadata.MetadataRelationship.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.Metadata> getAllParentMetadata()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.Metadata>) getParents(com.runwaysdk.system.metadata.MetadataRelationship.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.MetadataRelationship> getAllParentMetadataRel()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.MetadataRelationship>) getParentRelationships(com.runwaysdk.system.metadata.MetadataRelationship.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.system.metadata.MetadataRelationship getParentMetadataRel(com.runwaysdk.system.metadata.Metadata metadata)
  {
    com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.MetadataRelationship> iterator = (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.MetadataRelationship>) getRelationshipsWithParent(metadata, com.runwaysdk.system.metadata.MetadataRelationship.CLASS);
    try
    {
      if (iterator.hasNext())
      {
        return iterator.next();
      }
      else
      {
        return null;
      }
    }
    finally
    {
      iterator.close();
    }
  }
  
  public static BusinessSystem get(String oid)
  {
    return (BusinessSystem) com.runwaysdk.business.Business.get(oid);
  }
  
  public static BusinessSystem getByKey(String key)
  {
    return (BusinessSystem) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static BusinessSystem lock(java.lang.String oid)
  {
    BusinessSystem _instance = BusinessSystem.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static BusinessSystem unlock(java.lang.String oid)
  {
    BusinessSystem _instance = BusinessSystem.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
