package com.runwaysdk.system.graph;

@com.runwaysdk.business.ClassSignature(hash = 523099204)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ChangeFrequencyMaster.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ChangeFrequencyMasterQueryDTO extends com.runwaysdk.system.EnumerationMasterQueryDTO
{
private static final long serialVersionUID = 523099204;

  protected ChangeFrequencyMasterQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.graph.ChangeFrequencyMasterDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.graph.ChangeFrequencyMasterDTO>)super.getResultSet();
}
}
