/**
 * Copyright (c) 2013 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 1810580479)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to EntityCacheMaster.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class EntityCacheMasterBase extends com.runwaysdk.system.EnumerationMaster
{
  public final static String CLASS = "com.runwaysdk.system.metadata.EntityCacheMaster";
  public static java.lang.String CACHECODE = "cacheCode";
  public static java.lang.String DESCRIPTION = "description";
  private static final long serialVersionUID = 1810580479;
  
  public EntityCacheMasterBase()
  {
    super();
  }
  
  public Integer getCacheCode()
  {
    return com.runwaysdk.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(CACHECODE));
  }
  
  public void validateCacheCode()
  {
    this.validateAttribute(CACHECODE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getCacheCodeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.EntityCacheMaster.CLASS);
    return mdClassIF.definesAttribute(CACHECODE);
  }
  
  public String getDescription()
  {
    return getValue(DESCRIPTION);
  }
  
  public void validateDescription()
  {
    this.validateAttribute(DESCRIPTION);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getDescriptionMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.EntityCacheMaster.CLASS);
    return mdClassIF.definesAttribute(DESCRIPTION);
  }
  
  public void setDescription(String value)
  {
    if(value == null)
    {
      setValue(DESCRIPTION, "");
    }
    else
    {
      setValue(DESCRIPTION, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static EntityCacheMaster get(String id)
  {
    return (EntityCacheMaster) com.runwaysdk.business.Business.get(id);
  }
  
  public static EntityCacheMaster getByKey(String key)
  {
    return (EntityCacheMaster) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static EntityCacheMaster getEnumeration(String enumName)
  {
    return (EntityCacheMaster) com.runwaysdk.business.Business.getEnumeration(com.runwaysdk.system.metadata.EntityCacheMaster.CLASS ,enumName);
  }
  
  public static EntityCacheMaster lock(java.lang.String id)
  {
    EntityCacheMaster _instance = EntityCacheMaster.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static EntityCacheMaster unlock(java.lang.String id)
  {
    EntityCacheMaster _instance = EntityCacheMaster.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
