/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 315679883)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to IndexAttribute.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class IndexAttributeBase extends com.runwaysdk.system.metadata.MetadataRelationship
{
  public final static String CLASS = "com.runwaysdk.system.metadata.IndexAttribute";
  public static java.lang.String INDEXORDER = "indexOrder";
  private static final long serialVersionUID = 315679883;
  
  public IndexAttributeBase(String parentId, String childId)
  {
    super(parentId, childId);
  }
  
  public Integer getIndexOrder()
  {
    return com.runwaysdk.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(INDEXORDER));
  }
  
  public void validateIndexOrder()
  {
    this.validateAttribute(INDEXORDER);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getIndexOrderMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.IndexAttribute.CLASS);
    return mdClassIF.definesAttribute(INDEXORDER);
  }
  
  public void setIndexOrder(Integer value)
  {
    if(value == null)
    {
      setValue(INDEXORDER, "");
    }
    else
    {
      setValue(INDEXORDER, java.lang.Integer.toString(value));
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.system.metadata.MdIndex getParent()
  {
    return (com.runwaysdk.system.metadata.MdIndex) super.getParent();
  }
  
  public com.runwaysdk.system.metadata.MdAttributeConcrete getChild()
  {
    return (com.runwaysdk.system.metadata.MdAttributeConcrete) super.getChild();
  }
  
  public static IndexAttribute get(String id)
  {
    return (IndexAttribute) com.runwaysdk.business.Relationship.get(id);
  }
  
  public static IndexAttribute getByKey(String key)
  {
    return (IndexAttribute) com.runwaysdk.business.Relationship.get(CLASS, key);
  }
  
  public static IndexAttribute lock(java.lang.String id)
  {
    IndexAttribute _instance = IndexAttribute.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static IndexAttribute unlock(java.lang.String id)
  {
    IndexAttribute _instance = IndexAttribute.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
