package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = -1280599209)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdAttributeGraphReference.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MdAttributeGraphReferenceBase extends com.runwaysdk.system.metadata.MdAttributeConcrete
{
  public final static String CLASS = "com.runwaysdk.system.metadata.MdAttributeGraphReference";
  public static java.lang.String REFERENCEMDVERTEX = "referenceMdVertex";
  private static final long serialVersionUID = -1280599209;
  
  public MdAttributeGraphReferenceBase()
  {
    super();
  }
  
  public com.runwaysdk.system.metadata.MdVertex getReferenceMdVertex()
  {
    if (getValue(REFERENCEMDVERTEX).trim().equals(""))
    {
      return null;
    }
    else
    {
      return com.runwaysdk.system.metadata.MdVertex.get(getValue(REFERENCEMDVERTEX));
    }
  }
  
  public String getReferenceMdVertexOid()
  {
    return getValue(REFERENCEMDVERTEX);
  }
  
  public void validateReferenceMdVertex()
  {
    this.validateAttribute(REFERENCEMDVERTEX);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF getReferenceMdVertexMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.MdAttributeGraphReference.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF)mdClassIF.definesAttribute(REFERENCEMDVERTEX);
  }
  
  public void setReferenceMdVertex(com.runwaysdk.system.metadata.MdVertex value)
  {
    if(value == null)
    {
      setValue(REFERENCEMDVERTEX, "");
    }
    else
    {
      setValue(REFERENCEMDVERTEX, value.getOid());
    }
  }
  
  public void setReferenceMdVertexId(java.lang.String oid)
  {
    if(oid == null)
    {
      setValue(REFERENCEMDVERTEX, "");
    }
    else
    {
      setValue(REFERENCEMDVERTEX, oid);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static MdAttributeGraphReference get(String oid)
  {
    return (MdAttributeGraphReference) com.runwaysdk.business.Business.get(oid);
  }
  
  public static MdAttributeGraphReference getByKey(String key)
  {
    return (MdAttributeGraphReference) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static MdAttributeGraphReference lock(java.lang.String oid)
  {
    MdAttributeGraphReference _instance = MdAttributeGraphReference.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static MdAttributeGraphReference unlock(java.lang.String oid)
  {
    MdAttributeGraphReference _instance = MdAttributeGraphReference.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
