package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 1406860667)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdAttributeRatio.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MdAttributeRatioBase extends com.runwaysdk.system.metadata.MdAttributeConcrete
{
  public final static String CLASS = "com.runwaysdk.system.metadata.MdAttributeRatio";
  public static java.lang.String RATIO = "ratio";
  private static final long serialVersionUID = 1406860667;
  
  public MdAttributeRatioBase()
  {
    super();
  }
  
  public com.runwaysdk.system.Ratio getRatio()
  {
    if (getValue(RATIO).trim().equals(""))
    {
      return null;
    }
    else
    {
      return com.runwaysdk.system.Ratio.get(getValue(RATIO));
    }
  }
  
  public String getRatioId()
  {
    return getValue(RATIO);
  }
  
  public void validateRatio()
  {
    this.validateAttribute(RATIO);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF getRatioMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.MdAttributeRatio.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF)mdClassIF.definesAttribute(RATIO);
  }
  
  public void setRatio(com.runwaysdk.system.Ratio value)
  {
    if(value == null)
    {
      setValue(RATIO, "");
    }
    else
    {
      setValue(RATIO, value.getId());
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.system.metadata.AttributeRatio addgetReferencedRatio(com.runwaysdk.system.Ratio ratio)
  {
    return (com.runwaysdk.system.metadata.AttributeRatio) addChild(ratio, com.runwaysdk.system.metadata.AttributeRatio.CLASS);
  }
  
  public void removegetReferencedRatio(com.runwaysdk.system.Ratio ratio)
  {
    removeAllChildren(ratio, com.runwaysdk.system.metadata.AttributeRatio.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.Ratio> getAllgetReferencedRatio()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.Ratio>) getChildren(com.runwaysdk.system.metadata.AttributeRatio.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.AttributeRatio> getAllgetReferencedRatioRel()
  {
    return (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.AttributeRatio>) getChildRelationships(com.runwaysdk.system.metadata.AttributeRatio.CLASS);
  }
  
  @SuppressWarnings("unchecked")
  public com.runwaysdk.system.metadata.AttributeRatio getgetReferencedRatioRel(com.runwaysdk.system.Ratio ratio)
  {
    com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.AttributeRatio> iterator = (com.runwaysdk.query.OIterator<? extends com.runwaysdk.system.metadata.AttributeRatio>) getRelationshipsWithChild(ratio, com.runwaysdk.system.metadata.AttributeRatio.CLASS);
    try
    {
      if (iterator.hasNext())
      {
        return iterator.next();
      }
      else
      {
        return null;
      }
    }
    finally
    {
      iterator.close();
    }
  }
  
  public static MdAttributeRatio get(String id)
  {
    return (MdAttributeRatio) com.runwaysdk.business.Business.get(id);
  }
  
  public static MdAttributeRatio getByKey(String key)
  {
    return (MdAttributeRatio) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static MdAttributeRatio lock(java.lang.String id)
  {
    MdAttributeRatio _instance = MdAttributeRatio.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static MdAttributeRatio unlock(java.lang.String id)
  {
    MdAttributeRatio _instance = MdAttributeRatio.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
