package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 1676121873)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdAttributeEmbedded.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MdAttributeEmbeddedBase extends com.runwaysdk.system.metadata.MdAttributeConcrete
{
  public final static String CLASS = "com.runwaysdk.system.metadata.MdAttributeEmbedded";
  public static java.lang.String EMBEDDEDMDCLASS = "embeddedMdClass";
  private static final long serialVersionUID = 1676121873;
  
  public MdAttributeEmbeddedBase()
  {
    super();
  }
  
  public com.runwaysdk.system.metadata.MdClass getEmbeddedMdClass()
  {
    if (getValue(EMBEDDEDMDCLASS).trim().equals(""))
    {
      return null;
    }
    else
    {
      return com.runwaysdk.system.metadata.MdClass.get(getValue(EMBEDDEDMDCLASS));
    }
  }
  
  public String getEmbeddedMdClassOid()
  {
    return getValue(EMBEDDEDMDCLASS);
  }
  
  public void validateEmbeddedMdClass()
  {
    this.validateAttribute(EMBEDDEDMDCLASS);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF getEmbeddedMdClassMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.MdAttributeEmbedded.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF)mdClassIF.definesAttribute(EMBEDDEDMDCLASS);
  }
  
  public void setEmbeddedMdClass(com.runwaysdk.system.metadata.MdClass value)
  {
    if(value == null)
    {
      setValue(EMBEDDEDMDCLASS, "");
    }
    else
    {
      setValue(EMBEDDEDMDCLASS, value.getOid());
    }
  }
  
  public void setEmbeddedMdClassId(java.lang.String oid)
  {
    if(oid == null)
    {
      setValue(EMBEDDEDMDCLASS, "");
    }
    else
    {
      setValue(EMBEDDEDMDCLASS, oid);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static MdAttributeEmbedded get(String oid)
  {
    return (MdAttributeEmbedded) com.runwaysdk.business.Business.get(oid);
  }
  
  public static MdAttributeEmbedded getByKey(String key)
  {
    return (MdAttributeEmbedded) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static MdAttributeEmbedded lock(java.lang.String oid)
  {
    MdAttributeEmbedded _instance = MdAttributeEmbedded.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static MdAttributeEmbedded unlock(java.lang.String oid)
  {
    MdAttributeEmbedded _instance = MdAttributeEmbedded.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
