/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = -2074703911)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to VisibleDependency.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class VisibleDependencyBase extends com.runwaysdk.system.metadata.MetadataRelationship
{
  public final static String CLASS = "com.runwaysdk.system.metadata.VisibleDependency";
  public static java.lang.String CONDITION = "condition";
  private static final long serialVersionUID = -2074703911;
  
  public VisibleDependencyBase(String parentId, String childId)
  {
    super(parentId, childId);
  }
  
  public com.runwaysdk.system.metadata.FieldCondition getCondition()
  {
    if (getValue(CONDITION).trim().equals(""))
    {
      return null;
    }
    else
    {
      return com.runwaysdk.system.metadata.FieldCondition.get(getValue(CONDITION));
    }
  }
  
  public String getConditionId()
  {
    return getValue(CONDITION);
  }
  
  public void validateCondition()
  {
    this.validateAttribute(CONDITION);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getConditionMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.VisibleDependency.CLASS);
    return mdClassIF.definesAttribute(CONDITION);
  }
  
  public void setCondition(com.runwaysdk.system.metadata.FieldCondition value)
  {
    if(value == null)
    {
      setValue(CONDITION, "");
    }
    else
    {
      setValue(CONDITION, value.getOid());
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.system.metadata.MdField getParent()
  {
    return (com.runwaysdk.system.metadata.MdField) super.getParent();
  }
  
  public com.runwaysdk.system.metadata.MdField getChild()
  {
    return (com.runwaysdk.system.metadata.MdField) super.getChild();
  }
  
  public static VisibleDependency get(String oid)
  {
    return (VisibleDependency) com.runwaysdk.business.Relationship.get(oid);
  }
  
  public static VisibleDependency getByKey(String key)
  {
    return (VisibleDependency) com.runwaysdk.business.Relationship.get(CLASS, key);
  }
  
  public static VisibleDependency lock(java.lang.String oid)
  {
    VisibleDependency _instance = VisibleDependency.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static VisibleDependency unlock(java.lang.String oid)
  {
    VisibleDependency _instance = VisibleDependency.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
