/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = -1491830806)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to VisibilityModifierMaster.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class VisibilityModifierMasterBase extends com.runwaysdk.system.EnumerationMaster
{
  public final static String CLASS = "com.runwaysdk.system.metadata.VisibilityModifierMaster";
  public static java.lang.String JAVAVALUE = "javaValue";
  private static final long serialVersionUID = -1491830806;
  
  public VisibilityModifierMasterBase()
  {
    super();
  }
  
  public String getJavaValue()
  {
    return getValue(JAVAVALUE);
  }
  
  public void validateJavaValue()
  {
    this.validateAttribute(JAVAVALUE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getJavaValueMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.system.metadata.VisibilityModifierMaster.CLASS);
    return mdClassIF.definesAttribute(JAVAVALUE);
  }
  
  public void setJavaValue(String value)
  {
    if(value == null)
    {
      setValue(JAVAVALUE, "");
    }
    else
    {
      setValue(JAVAVALUE, value);
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static VisibilityModifierMaster get(String id)
  {
    return (VisibilityModifierMaster) com.runwaysdk.business.Business.get(id);
  }
  
  public static VisibilityModifierMaster getByKey(String key)
  {
    return (VisibilityModifierMaster) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static VisibilityModifierMaster getEnumeration(String enumName)
  {
    return (VisibilityModifierMaster) com.runwaysdk.business.Business.getEnumeration(com.runwaysdk.system.metadata.VisibilityModifierMaster.CLASS ,enumName);
  }
  
  public static VisibilityModifierMaster lock(java.lang.String id)
  {
    VisibilityModifierMaster _instance = VisibilityModifierMaster.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static VisibilityModifierMaster unlock(java.lang.String id)
  {
    VisibilityModifierMaster _instance = VisibilityModifierMaster.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
