/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.system.metadata;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 *
 * @author Autogenerated by RunwaySDK
 */
@com.runwaysdk.business.ClassSignature(hash = 533296608)
public enum VisibilityModifier implements com.runwaysdk.business.BusinessEnumeration
{
  PROTECTED(),
  
  PUBLIC();
  
  public static final java.lang.String CLASS = "com.runwaysdk.system.metadata.VisibilityModifier";
  private com.runwaysdk.system.metadata.VisibilityModifierMaster enumeration;
  
  private synchronized void loadEnumeration()
  {
    com.runwaysdk.system.metadata.VisibilityModifierMaster enu = com.runwaysdk.system.metadata.VisibilityModifierMaster.getEnumeration(this.name());
    setEnumeration(enu);
  }
  
  private synchronized void setEnumeration(com.runwaysdk.system.metadata.VisibilityModifierMaster enumeration)
  {
    this.enumeration = enumeration;
  }
  
  public String getJavaValue()
  {
    loadEnumeration();
    return enumeration.getJavaValue();
  }
  
  public java.lang.String getOid()
  {
    loadEnumeration();
    return enumeration.getOid();
  }
  
  public java.lang.String getEnumName()
  {
    loadEnumeration();
    return enumeration.getEnumName();
  }
  
  public java.lang.String getDisplayLabel()
  {
    loadEnumeration();
    return enumeration.getDisplayLabel().getValue(com.runwaysdk.session.Session.getCurrentLocale());
  }
  
  public static VisibilityModifier get(String oid)
  {
    for (VisibilityModifier e : VisibilityModifier.values())
    {
      if (e.getOid().equals(oid))
      {
        return e;
      }
    }
    return null;
  }
  
}
