package com.runwaysdk.system;

@com.runwaysdk.business.ClassSignature(hash = 362238344)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MetadataParameter.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MetadataParameterQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 362238344;

  protected MetadataParameterQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.MetadataParameterDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.MetadataParameterDTO>)super.getResultSet();
}
}
