package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 1263632258)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdMobileHeaderHeaderText.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MdMobileHeaderHeaderTextQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 1263632258;

  protected MdMobileHeaderHeaderTextQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.metadata.MdMobileHeaderHeaderTextDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.metadata.MdMobileHeaderHeaderTextDTO>)super.getResultSet();
}
}
