package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = -588434353)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdWebGeo.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MdWebGeoQueryDTO extends com.runwaysdk.system.metadata.MdWebAttributeQueryDTO
{
private static final long serialVersionUID = -588434353;

  protected MdWebGeoQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.metadata.MdWebGeoDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.metadata.MdWebGeoDTO>)super.getResultSet();
}
}
