package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = -1555799616)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MdWebAttribute.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MdWebAttributeQueryDTO extends com.runwaysdk.system.metadata.MdWebFieldQueryDTO
{
private static final long serialVersionUID = -1555799616;

  protected MdWebAttributeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.metadata.MdWebAttributeDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.metadata.MdWebAttributeDTO>)super.getResultSet();
}
}
