package com.runwaysdk.system.metadata;

@com.runwaysdk.business.ClassSignature(hash = 518105509)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MobileGridField.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MobileGridFieldQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
{
@SuppressWarnings("unused")
private static final long serialVersionUID = 518105509;

  protected MobileGridFieldQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.metadata.MobileGridFieldDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.metadata.MobileGridFieldDTO>)super.getResultSet();
}
}
