package ${package};

@com.runwaysdk.business.ClassSignature(hash = -976731527)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to HelloWorld.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class HelloWorldQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -976731527;

  protected HelloWorldQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends ${package}.HelloWorldDTO> getResultSet()
{
  return (java.util.List<? extends ${package}.HelloWorldDTO>)super.getResultSet();
}
}
