/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.jstest;

@com.runwaysdk.business.ClassSignature(hash = 595253420)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to TestException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class TestExceptionBase extends com.runwaysdk.business.SmartException implements com.runwaysdk.generation.loader.
{
  public final static String CLASS = "com.runwaysdk.jstest.TestException";
  public static java.lang.String EXCHAR = "exChar";
  public static java.lang.String EXINT = "exInt";
  public static java.lang.String OID = "oid";
  private static final long serialVersionUID = 595253420;
  
  public TestExceptionBase()
  {
    super();
  }
  
  public TestExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public TestExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public TestExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getExChar()
  {
    return getValue(EXCHAR);
  }
  
  public void validateExChar()
  {
    this.validateAttribute(EXCHAR);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getExCharMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.jstest.TestException.CLASS);
    return mdClassIF.definesAttribute(EXCHAR);
  }
  
  public void setExChar(String value)
  {
    if(value == null)
    {
      setValue(EXCHAR, "");
    }
    else
    {
      setValue(EXCHAR, value);
    }
  }
  
  public Integer getExInt()
  {
    return com.runwaysdk.constants.MdAttributeIntegerUtil.getTypeSafeValue(getValue(EXINT));
  }
  
  public void validateExInt()
  {
    this.validateAttribute(EXINT);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getExIntMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.jstest.TestException.CLASS);
    return mdClassIF.definesAttribute(EXINT);
  }
  
  public void setExInt(Integer value)
  {
    if(value == null)
    {
      setValue(EXINT, "");
    }
    else
    {
      setValue(EXINT, java.lang.Integer.toString(value));
    }
  }
  
  public String getOid()
  {
    return getValue(OID);
  }
  
  public void validateId()
  {
    this.validateAttribute(OID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getOidMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.jstest.TestException.CLASS);
    return mdClassIF.definesAttribute(OID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{exChar}", this.getExChar());
    message = replace(message, "{exInt}", this.getExInt());
    message = replace(message, "{oid}", this.getOid());
    return message;
  }
  
}
