package com.runwaysdk.system.ontology;

@com.runwaysdk.business.ClassSignature(hash = 888596018)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ClassifierDisplayLabel.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ClassifierDisplayLabelQueryDTO extends com.runwaysdk.business.StructQueryDTO
{
private static final long serialVersionUID = 888596018;

  protected ClassifierDisplayLabelQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.system.ontology.ClassifierDisplayLabelDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.system.ontology.ClassifierDisplayLabelDTO>)super.getResultSet();
}
}
