/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK GIS(tm).
 *
 * Runway SDK GIS(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK GIS(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK GIS(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.gis.constants;

public enum CountryInfo 
{
  AFGHANISTAN("Afghanistan", "93"),
  ALBANIA("Albania", "355"),
  ALGERIA("Algeria", "213"),
  AMERICAN_SAMOA("AmericanSamoa", "1-684"),
  ANDORA("Andora", "376"),
  ANGOLA("Angola", "244"),
  ANGUILLA("Anguilla", "1-264"),
  ANTARCTICA("Antarctica", "672"),
  ANTIQUA_AND_BARBUDA("AntiguaAndBarbuda", "1-268"),
  ARGENTINA("Argentina", "54"),
  ARMENIA("Armenia", "374"),
  ARUBA("Aruba", "297"),
  AUSTRALIA("Australia", "61"),
  AUSTRIA("Austria", "43"),
  AZERBAIJAN("Azerbaijan", "994"),
  BAHAMAS("Bahamas", "1-242"),
  BAHRAIN("Bahrain", "973"),
  BANGLADESH("Bangladesh", "880"),
  BARBADOS("Barbados", "1-246"),
  BELARUS("Belarus", "375"),
  BELGIUM("Belgium", "32"),
  BELIZE("Belize", "501"),
  BENIN("Benin", "229"),
  BERMUDA("Bermuda", "1-441"),
  BHUTAN("Bhutan", "975"),
  BOLIVIA("Bolivia", "591"),
  BOSNIA_AND_HERZEGOVINA("BosniaAndHerzegovina", "387"),
  BOTSWANA("Botswana", "267"),
  BRAZIL("Brazil", "55"),
  BRITISH_INDIAN_OCEAN_TERRITORY("BritishIndianOceanTerritory", "246"),
  BRITISH_VIRGIN_ISLANDS("BritishVirginIslands", "1-284"),
  BRUNEI("Brunei", "673"),
  BULGARIA("Bulgaria", "359"),
  BURKINA_FASO("BurkinaFaso", "226"),
  BURUNDI("Burundi", "257"),
  CAMBODIA("Cambodia", "855"),
  CAMEROON("Cameroon", "237"),
  CANADA("Canada", "1"),
  CAPE("Cape Verde", "238"),
  CAYMAN_ISLANDS("CaymanIslands", "1-345"),
  CENTRAL_AFRICAN_REPUBLIC("CentralAfricanRepublic", "236"),
  CHAD("Chad", "235"),
  CHILE("Chile", "56"),
  CHINA("China", "86"),
  CHRISTMAS_ISLAND("ChristmasIsland", "61"),
  COCOS_ISLANDS("CocosIslands", "61"),
  COLOMBIA("Colombia", "57"),
  COMOROS("Comoros", "269"),
  COOK_ISLANDS("CookIslands", "682"),
  COSTA_RICA("CostaRica", "506"),
  CROATIA("Croatia", "385"),
  CUBA("Cuba", "53"),
  CURACAO("Curacao", "599"),
  CYPRUS("Cyprus", "357"),
  CZECH_REPUBLIC("CzechRepublic", "420"),
  DEMOCRATIC_REPUBLIC_OF_THE_CONGO("DemocraticRepublicOfTheCongo", "243"),
  DENMARK("Denmark", "45"),
  DJIBOUTI("Djibouti", "253"),
  DOMINICA("Dominica", "1-767"),
  DOMINICAN_REPUBLIC("DominicanRepublic", "1-809, 1-829, 1-849"),
  EAST_TIMOR("EastTimor", "670"),
  ECUADOR("Ecuador", "593"),
  EGYPT("Egypt", "20"),
  EL_SALVADOR("ElSalvador", "503"),
  EQUATORIAL_GUINEA("EquatorialGuinea", "240"),
  ERITREA("Eritrea", "291"),
  ESTONIA("Estonia", "372"),
  ETHIOPIA("Ethiopia", "251"),
  FALKLAND_ISLANDS("FalklandIslands", "500"),
  FAROE_ISLANDS("FaroeIslands", "298"),
  FIJI("Fiji", "679"),
  FINLAND("Finland", "358"),
  FRANCE("France", "33"),
  FRENCH_POLYNESIA("FrenchPolynesia", "689"),
  GABON("Gabon", "241"),
  GAMBIA("Gambia", "220"),
  GEOGIA("Georgia", "995"),
  GERMANY("Germany", "49"),
  GHANA("Ghana", "233"),
  GIBRALTAR("Gibraltar", "350"),
  GREECE("Greece", "30"),
  GREENLAND("Greenland", "299"),
  GRENADA("Grenada", "1-473"),
  GUAM("Guam", "1-671"),
  GUATEMALA("Guatemala", "502"),
  GUERNSEY("Guernsey", "44-1481"),
  GUINEA("Guinea", "224"),
  GUINEA_BISSAU("Guinea-Bissau", "245"),
  GUYANA("Guyana", "592"),
  HAITI("Haiti", "509"),
  HONDURAS("Honduras", "504"),
  HONG_KONG("HongKong", "852"),
  HUNGARY("Hungary", "36"),
  ICELAND("Iceland", "354"),
  INDIA("India", "91"),
  INDONESIA("Indonesia", "62"),
  IRAN("Iran", "98"),
  IRAQ("Iraq", "964"),
  IRELAND("Ireland", "353"),
  ISLE_OF_MAN("IsleOfMan", "44-1624"),
  ISRAEL("Israel", "972"),
  ITALY("Italy", "39"),
  IVORY_COAST("IvoryCoast", "225"),
  JAMAICA("Jamaica", "1-876"),
  JAPAN("Japan", "81"),
  JERSEY("Jersey", "44-1534"),
  JORDAN("Jordan", "962"),
  KAZAKHSTAN("Kazakhstan", "7"),
  KENYA("Kenya", "254"),
  KIRIBATI("Kiribati", "686"),
  KOSOVO("Kosovo", "383"),
  KUWAIT("Kuwait", "965"),
  KYRGYZSTAN("Kyrgyzstan", "996"),
  LAOS("Laos", "856"),
  LATVIA("Latvia", "371"),
  LEBANON("Lebanon", "961"),
  LESOTHO("Lesotho", "266"),
  LIBERIA("Liberia", "231"),
  LIBYA("Libya", "218"),
  LIECHTENSTEIN("Liechtenstein", "423"),
  LITHUANIA("Lithuania", "370"),
  LUXEMBOURG("Luxembourg", "352"),
  MACAO("Macao", "853"),
  MACEDONIA("Macedonia", "389"),
  MADAGASCAR("Madagascar", "261"),
  MALAWI("Malawi", "265"),
  MALAYSIA("Malaysia", "60"),
  MALDIVES("Maldives", "960"),
  MALI("Mali", "223"),
  MALTA("Malta", "356"),
  MARSHAL_ISLANDS("MarshallIslands", "692"),
  MAURITANIA("Mauritania", "222"),
  MAURITIUS("Mauritius", "230"),
  MAYOTTE("Mayotte", "262"),
  MEXICO("Mexico", "52"),
  MICRONESIA("Micronesia", "691"),
  MOLDOVA("Moldova", "373"),
  MONACO("Monaco", "377"),
  MONGOLIA("Mongolia", "976"),
  MONTENEGRO("Montenegro", "382"),
  MONTSERRAT("Montserrat", "1-664"),
  MOROCCO("Morocco", "212"),
  MOZAMBIQUE("Mozambique", "258"),
  MYANMAR("Myanmar", "95"),
  NAMIBIA("Namibia", "264"),
  NAURU("Nauru", "674"),
  NEPAL("Nepal", "977"),
  NETHERLANDS("Netherlands", "31"),
  NETHERLANDS_ANTILLES("NetherlandsAntilles", "599"),
  NEW_CALEDONIA("NewCaledonia", "687"),
  NEW_ZEALAND("NewZealand", "64"),
  NICARAGUA("Nicaragua", "505"),
  NIGER("Niger", "227"),
  NIGERIA("Nigeria", "234"),
  NIVE("Niue", "683"),
  NORTH_KOREA("NorthKorea", "850"),
  NORTHERN_MARIANA_ISLANDS("NorthernMarianaIslands", "1-670"),
  NORWAY("Norway", "47"),
  OMAN("Oman", "968"),
  PAKISTAN("Pakistan", "92"),
  PALAU("Palau", "680"),
  PALESTINE("Palestine", "970"),
  PANAMA("Panama", "507"),
  PAPUA_NEW_GUINEA("PapuaNewGuinea", "675"),
  PARAGUAY("Paraguay", "595"),
  PERU("Peru", "51"),
  PHILIPPINES("Philippines", "63"),
  PITCAIRN("Pitcairn", "64"),
  POLAND("Poland", "48"),
  PORTUGAL("Portugal", "351"),
  PUERTO_RICO("PuertoRico", "1-787, 1-939"),
  QUATAR("Qatar", "974"),
  REPUBLIC_OF_THE_CONGO("RepublicOfTheCongo", "242"),
  REUNION("Reunion", "262"),
  ROMANIA("Romania", "40"),
  RUSSIA("Russia", "7"),
  RWANDA("Rwanda", "250"),
  SAINT_BARTHELEMY("SaintBarthelemy", "590"),
  SAINT_HELENA("SaintHelena", "290"),
  SAINT_KITTS_AND_NEVIS("SaintKittsAndNevis", "1-869"),
  SAINT_LUCIA("SaintLucia", "1-758"),
  SAINT_MARTIN("SaintMartin", "590"),
  SAINT_PIERRE("SaintPierreAndMiquelon", "508"),
  SAINT_VINCENT_AND_THE_GRENADINES("SaintVincentAndTheGrenadines", "1-784"),
  SAMOA("Samoa", "685"),
  SAN_MARINO("SanMarino", "378"),
  SAO_TOME_AND_PRINCIPE("SaoTomeAndPrincipe", "239"),
  SAUDI_ARABIA("SaudiArabia", "966"),
  SENEGAL("Senegal", "221"),
  SERBIA("Serbia", "381"),
  SEYCHELLES("Seychelles", "248"),
  SIERRA_LEONE("SierraLeone", "232"),
  SINGAPORE("Singapore", "65"),
  SAINT_MAARTEN("SaintMaarten", "1-721"),
  SLOVAKIA("Slovakia", "421"),
  SLOVENIA("Slovenia", "386"),
  SOLOMON_ISLANDS("SolomonIslands", "677"),
  SOMALIA("Somalia", "252"),
  SOUTH_AFRICA("SouthAfrica", "27"),
  SOUTH_KOREA("SouthKorea", "82"),
  SOUTH_SUDAN("SouthSudan", "211"),
  SPAIN("Spain", "34"),
  SRI_LANKA("SriLanka", "94"),
  SUDAN("Sudan", "249"),
  SURINAME("Suriname", "597"),
  SVALBARD_AND_JAN_MAYEN("SvalbardAndJanMayen", "47"),
  SWAZILAND("Swaziland", "268"),
  SWEDEN("Sweden", "46"),
  SWITZERLAND("Switzerland", "41"),
  SYRIA("Syria", "963"),
  TAIWAN("Taiwan", "886"),
  TAJIKISTAN("Tajikistan", "992"),
  TANZANIA("Tanzania", "255"),
  THAILAND("Thailand", "66"),
  TOGO("Togo", "228"),
  TOKELAU("Tokelau", "690"),
  TONGA("Tonga", "676"),
  TRINIDAD_AND_TOBAGO("TrinidadAndTobago", "1-868"),
  TUNISIA("Tunisia", "216"),
  TURKEY("Turkey", "90"),
  TURKMENISTAN("Turkmenistan", "993"),
  TURKS_AND_CAICOS_ISLANDS("TurksAndCaicosIslands", "1-649"),
  TUVALU("Tuvalu", "688"),
  US_VIRGIN_ISLANDS("USVirginIslands", "1-340"),
  UGANDA("Uganda", "256"),
  UKRAINE("kraine", "380"),
  UNITED_ARAB_EMIRATES("UnitedArabEmirates", "971"),
  UNITED_KINGDOM("UnitedKingdom", "44"),
  UNITED_STATES_OF_AMERICA("UnitedStatesOfAmerica", "1"),
  URUGUAY("Uruguay", "598"),
  UZBEKISTAN("Uzbekistan", "998"),
  VANUATU("Vanuatu", "678"),
  VATICAN("Vatican", "379"),
  VENEZUELA("Venezuela", "58"),
  VIETNAM("Vietnam", "84"),
  WALLIS_AND_FUTUNA("WallisAndFutuna", "681"),
  WESTERN_SAHARA("WesternSahara", "212"),
  YEMEN("Yemen", "967"),
  ZAMBIA("Zambia", "260"),
  ZIMBABWE("Zimbabwe", "263");
  
  
  private String countryName;
  private String countryCode;
  
  private CountryInfo(String _countryName, String _countryCode)
  {
    this.countryName = _countryName;
    this.countryCode = _countryCode;
  }
  
  public String countryName()
  {
    return this.countryName;
  }
  
  public String countryCode()
  {
    return this.countryCode;
  }
  
}
